# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test1',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test10',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test2',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test3',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test4',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test5',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test6',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test7',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test8',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='test9',
            field=models.IntegerField(null=True),
        ),
    ]
