# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-08 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('login', '0002_auto_20170708_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isAdmin', models.BooleanField()),
                ('score', models.IntegerField()),
                ('level', models.IntegerField()),
                ('test1', models.IntegerField(null=True)),
                ('test2', models.IntegerField(null=True)),
                ('test3', models.IntegerField(null=True)),
                ('test4', models.IntegerField(null=True)),
                ('test5', models.IntegerField(null=True)),
                ('test6', models.IntegerField(null=True)),
                ('test7', models.IntegerField(null=True)),
                ('test8', models.IntegerField(null=True)),
                ('test9', models.IntegerField(null=True)),
                ('test10', models.IntegerField(null=True)),
                ('test', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
